---
- name: Create repository containment
  file:
    path: "{{ git_repos.containment }}"
    state: directory
    mode: 0700
    owner: "{{ ansible_ssh_user }}"
  register: git_repos_touch_log
  changed_when: git_repos_touch_log.diff.before.state is defined and git_repos_touch_log.diff.before.state != "directory"

- name: Cloning git repositories to containment
  git:
    repo: "{{ item.url }}"
    dest: "{{ git_repos.containment + '/' + item.name }}"
    update: yes
  with_items: "{{ git_repos.repositories }}"
  when: git_repos.repositories